#! /bin/bash

# MicroNucleus launcher by Steve Sanbeg

# This is intended as a drop-in replacement for the Digispark program
# of the same name.  Its role is to translate the avrdude syntax used
# by Arduino IDE into the equivalent micronucleus call, as well as to
# print some clearer messages to the terminal window.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

bin=$(dirname "$0")
options=$(getopt -n "$0" -o nc:U: --long timeout: -- "$@")
if [ $? -ne 0 ]
then
    exit 1
fi

die() {
    echo "$0: $1" >&2;
    exit 1;
}

timeout=60
type='intel-hex'
file=''
exec=exec

eval set -- "$options"
while true; do
    case "$1" in
    -c)
        programmer="$2"
	shift
        ;;
    -n)
	exec=echo;;
    -U)
	str="$2"
	mem_op=$(echo "$str" | cut -d: -f1,2)
	[ "$mem_op" = "flash:w" ] || die "Only writing to flash is supported."
	
	file=$(echo "$str" | cut -d: -f3) # the file to write

	format=$(echo "$str" | cut -d: -f4) # option, should be i, but r may be supported.
	case $format in
	    i|'') type='intel-hex';;
	    r) type='raw';;
	    *) die "Unsupported file type: $format";;
	esac
	;;
    --timeout)
	timeout="$2"
	shift;;
    --)
	shift
	break;;
    esac
    shift
done

# check that -U was specified, and we got something that could be a file
[ -n "$file" ] || die "No file specified!"

# fail fast, sanity check file before we plug in & connect; should never happen from Adruino IDE
:< "$file" || exit 1

echo "Plug in or reset device now (will timeout in $timeout seconds)..."
$exec "$bin/micronucleus" --type "$type" --timeout $timeout --run --no-ansi "$file"
